name: Continuous Integration

on:
  pull_request:
    branches:
      - master

jobs:

  lint:
    uses: MatthewZito/.github/.github/workflows/yarn_script_run.yml@master
    with:
      script_name: lint

  stylelint:
    uses: MatthewZito/.github/.github/workflows/yarn_script_run.yml@master
    with:
      script_name: lint:css

  typecheck:
    uses: MatthewZito/.github/.github/workflows/yarn_script_run.yml@master
    with:
      script_name: typecheck

  unit_test:
    uses: MatthewZito/.github/.github/workflows/yarn_script_run.yml@master
    with:
      script_name: test:unit

  e2e_test:
    uses: MatthewZito/.github/.github/workflows/yarn_script_run.yml@master
    with:
      script_name: test:e2e:ci
