name: Continuous Integration

on:
  pull_request:
    branches:
      - master

jobs:

  lint:
    uses: MatthewZito/.github/.github/workflows/yarn_script_run.yml@master
    with:
      script_name: lint

  stylelint:
    uses: MatthewZito/.github/.github/workflows/yarn_script_run.yml@master
    with:
      script_name: lint:css

  typecheck:
    uses: MatthewZito/.github/.github/workflows/yarn_script_run.yml@master
    with:
      script_name: typecheck

  unit_test:
    uses: MatthewZito/.github/.github/workflows/yarn_script_run.yml@master
    with:
      script_name: test:unit

  # TODO run in parallel
  # TODO test on different browsers
  e2e_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'
          cache: 'yarn'
      - run: yarn install
      - name: Run E2E tests
        uses: cypress-io/github-action@v2
        with:
          build: yarn build
          start: yarn serve
          browser: chrome
        env:
          CYPRESS_SUPPORT: "y"
